title: Zethesis Research & Engineering
description: Advanced simulation, numerical methods and scientific software for industrial engineering.
url: "https://www.zethesis.eu"
baseurl: ""

theme: minima

author: Robert Smith, PhD
email: contact@zethesis.eu

header_pages:
  - services.md
  - technical-notes.md
  - about.md
  - contact.md
plugins:
  - jekyll-feed
